# Generated by Django 4.2.30 on 2026-10-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=150)),
                ('caller_number', models.CharField(max_length=20)),
                ('duration_secs', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed'), ('dropped', 'Dropped'), ('voicemail', 'Voicemail')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
